package app.ui.main;

import app.ui.event.EventFrame;
import app.ui.expense.ExpenseFrame;

public class MainFrame extends javax.swing.JFrame {

    public MainFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddEvento = new javax.swing.JButton();
        btnAddViatico = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddEvento.setText("Registrar Evento");
        btnAddEvento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEventoActionPerformed(evt);
            }
        });

        btnAddViatico.setText("Registro Viatico");
        btnAddViatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddViaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEvento)
                    .addComponent(btnAddViatico))
                .addContainerGap(270, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddEvento)
                .addGap(18, 18, 18)
                .addComponent(btnAddViatico)
                .addContainerGap(212, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddEventoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEventoActionPerformed
        EventFrame f1 = new EventFrame();//Crear el Frame1 XD
        f1.setVisible(true);//Muestre el frame1
        dispose();//Eliminar el Frame actual
    }//GEN-LAST:event_btnAddEventoActionPerformed

    private void btnAddViaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddViaticoActionPerformed
        ExpenseFrame f1 = new ExpenseFrame();//Crear el Frame1 XD
        f1.setVisible(true);//Muestre el frame1
        dispose();//Eliminar el Frame actual
    }//GEN-LAST:event_btnAddViaticoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEvento;
    private javax.swing.JButton btnAddViatico;
    // End of variables declaration//GEN-END:variables
}
